# Generated by Django 3.1.12 on 2025-05-21 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('has_uppercase', models.BooleanField(default=True)),
                ('has_lowercase', models.BooleanField(default=True)),
                ('has_digits', models.BooleanField(default=True)),
                ('has_special', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['created_at'], name='generator_p_created_addca8_idx'),
        ),
    ]
